import type { Metadata } from "next";
import './globals.scss';
import './normalize.css';
import localFont from "next/font/local";

const roboto = localFont({
  src: [
    {
      path: './fonts/roboto/roboto.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/roboto/robotobold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/roboto/robotoitalic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/roboto/robotobolditalic.woff2',
      weight: '700',
      style: 'italic',
    },
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
